apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apprise-consumer-egress-policy
  namespace: analyplat
spec:
  egress:
    - {}
  podSelector:
    matchLabels:
      networking/allow-internet-egress: "true"
  policyTypes:
    - Egress